# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kiekebo-test',
                'doc_host': 'https://ssmeets.github.io',
                'git_url': 'https://github.com/ssmeets/kiekebo-test',
                'lib_path': 'kiekebo_test'},
  'syms': {'kiekebo_test.core': {'kiekebo_test.core.foo': ('core.html#foo', 'kiekebo_test/core.py')}}}
